config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gpg-agent.conf:
    dst: ~/.gnupg/gpg-agent.conf
    src: gnupg/gpg-agent.conf
  f_gpg.conf:
    dst: ~/.gnupg/gpg.conf
    src: gnupg/gpg.conf
    actions:
    - gpg-key-import
profiles:
  common:
    dotfiles:
    - f_gitconfig
    - f_gpg-agent.conf
    - f_gpg.conf
  idealo:
    dotfiles: []
    include:
    - common
    variables:
      git_email: tobias.vollmer@idealo.de
      git_user: Tobias Vollmer
variables:
  git_email: info@tvollmer.de
  git_user: 5nafu
actions:
  gpg-key-import: gpg  --keyserver https://key.tvollmer.de --recv-keys 0xd5fd9e5580e5e506

