actions:
  post:
    chmod_gnupg: chmod 700 ~/.gnupg
    chmod_ssh: chmod 700 ~/.ssh
    gpg-card-import: read -p "insert your keyfob and press enter" ready && gpg --card-status
    gpg-key-import: gpg --keyserver https://key.tvollmer.de --recv-keys 0xCD7583FE6D62D2A9
      && echo "16142EF211C6D2340A0B08F0CD7583FE6D62D2A9:6:" | gpg --import-ownertrust
    enable_bash_it: ln -s {{@@ _dotdrop_dotpath @@}}/bash_it_enabled {{@@ _dotdrop_dotpath @@}}/bash_it/enabled
    install_vim_plugins: vim +PlugUpgrade +PlugUpdate +qall
    run_macos_sh: {{@@ macos_config_script @@}}
config:
  backup: false
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: true
  showdiff: false
  workdir: ~/.config/dotdrop
  link_on_import: nolink
  minversion: 0.29.5
dotfiles:
  d_autostart:
    dst: ~/.config/autostart
    src: config/autostart
  d_bash_it:
    dst: ~/.bash_it
    link: link
    src: bash_it
    actions:
    - enable_bash_it
  d_kubectx:
    dst: ~/.kubectx
    link: link
    src: kubectx
  d_bashrc.d:
    dst: ~/.bashrc.d
    src: bashrc.d
  d_kubeconfig:
    dst: ~/.kube/config.d
    src: kube_config.d
    trans_read: gpgdir
    trans_write: gpgdir
    chmod: '775'
  d_bin:
    dst: ~/bin
    src: bin
    chmod: '755'
    actions:
    - run_macos_sh
  d_config_autorandr:
    dst: ~/.config/autorandr
    src: config/autorandr
  d_fonts:
    dst: "{{@@ font_directory @@}}"
    src: local/share/fonts
  f_aws_config:
    dst: ~/.aws/config
    src: aws/config
    trans_read: gpg
    trans_write: gpg
  f_base.cfg:
    dst: ~/.config/terminology/config/standard/base.cfg
    src: config/terminology/config/standard/base.cfg
  f_bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_config_xfce4_helpers.rc:
    dst: ~/.config/xfce4/helpers.rc
    src: config/xfce4/helpers.rc
  f_custom-terminalemulator.desktop:
    dst: ~/.local/share/xfce4/helpers/custom-TerminalEmulator.desktop
    src: local/share/xfce4/helpers/custom-TerminalEmulator.desktop
  f_custom-webbrowser.desktop:
    dst: ~/.local/share/xfce4/helpers/custom-WebBrowser.desktop
    src: local/share/xfce4/helpers/custom-WebBrowser.desktop
  f_dir_colors:
    dst: ~/.dir_colors
    src: dir_colors
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gpg-agent.conf:
    actions:
    - chmod_gnupg
    dst: ~/.gnupg/gpg-agent.conf
    src: gnupg/gpg-agent.conf
  f_gpg.conf:
    actions:
    - chmod_gnupg
    - gpg-key-import
    - gpg-card-import
    dst: ~/.gnupg/gpg.conf
    src: gnupg/gpg.conf
    chmod: '644'
  f_irssi_config:
    dst: ~/.irssi/config
    src: irssi/config
    trans_read: gpg
    trans_write: gpg
  f_ssh_config:
    actions:
    - chmod_ssh
    dst: ~/.ssh/config
    src: ssh/config
  f_ssh_config_01_global:
    actions:
    - chmod_ssh
    dst: ~/.ssh/config.d/01_global
    src: ssh/config.d/01_global
  f_ssh_config_10_idealo:
    actions:
    - chmod_ssh
    dst: ~/.ssh/config.d/10_idealo
    src: ssh/config.d/10_idealo
    trans_read: gpg
    trans_write: gpg
  f_ssh_config_10_tvollmer:
    actions:
    - chmod_ssh
    dst: ~/.ssh/config.d/10_tvollmer
    src: ssh/config.d/10_tvollmer
    trans_read: gpg
    trans_write: gpg
  f_sshcontrol:
    actions:
    - chmod_ssh
    dst: ~/.gnupg/sshcontrol
    src: gnupg/sshcontrol
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_xdefaults:
    dst: ~/.Xdefaults
    src: Xdefaults
  f_xfce4-keyboard-shortcuts.xml:
    dst: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
    src: config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
  f_kube_config:
    dst: ~/.kube/config
    src: kube/config
    trans_read: gpg
    trans_write: gpg
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_vim_colors_tomorrow-night.vim:
    src: vim/colors/Tomorrow-Night.vim
    dst: ~/.vim/colors/Tomorrow-Night.vim
  f_vim_colors_tomorrow-night-bright.vim:
    src: vim/colors/Tomorrow-Night-Bright.vim
    dst: ~/.vim/colors/Tomorrow-Night-Bright.vim
  f_vidalia_vidalia.conf:
    src: vidalia/vidalia.conf
    dst: ~/.vidalia/vidalia.conf
    trans_read: gpg
    trans_write: gpg
  f_ssh_authorized_keys:
    src: ssh/authorized_keys
    dst: ~/.ssh/authorized_keys
  f_nut-monitor_favorites.ini:
    src: nut-monitor/favorites.ini
    dst: ~/.nut-monitor/favorites.ini
    trans_read: gpg
    trans_write: gpg
  f_bashrc.andor:
    src: bashrc.andor
    dst: ~/.bashrc.andor
    trans_read: gpg
    trans_write: gpg
  f_docker_config.json:
    src: docker/config.json
    dst: ~/.docker/config.json
    trans_read: gpg
    trans_write: gpg
    chmod: '600'
  f_arm_armrc:
    src: arm/armrc
    dst: ~/.arm/armrc
    trans_read: gpg
    trans_write: gpg
  f_config_xfce4_xfconf_xfce-perchannel-xml_xsettings.xml:
    src: config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
    dst: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
  f_config_redshift.conf:
    src: config/redshift.conf
    dst: ~/.config/redshift.conf
profiles:
  common:
    dotfiles:
    - f_gitconfig
    - f_gpg-agent.conf
    - f_gpg.conf
    - f_aws_config
    - d_bin
    - d_bash_it
    - d_kubectx
    - d_bashrc.d
    - f_bashrc
    - f_bash_profile
    - f_dir_colors
    - f_sshcontrol
    - f_ssh_config
    - f_ssh_config_01_global
    - f_ssh_config_10_tvollmer
    - f_tmux.conf
  idealo:
    dotfiles:
    - d_config_autorandr
    - d_kubeconfig
    - f_ssh_config_10_idealo
    include:
    - common
    - linux
    variables:
      git_email: tobias.vollmer@idealo.de
      git_user: Tobias Vollmer
      MailReader: evolution
      WebBrowser: google-chrome
  andor:
    include:
    - common
    - linux
    dotfiles:
    - f_vidalia_vidalia.conf
    - f_nut-monitor_favorites.ini
    - f_bashrc.andor
    - f_arm_armrc
    - f_config_xfce4_xfconf_xfce-perchannel-xml_xsettings.xml
    - f_irssi_config
  linux:
    dotfiles:
    - d_autostart
    - f_base.cfg
    - f_xfce4-keyboard-shortcuts.xml
    - d_fonts
    - f_custom-terminalemulator.desktop
    - f_custom-webbrowser.desktop
    - f_xdefaults
    - f_config_xfce4_helpers.rc
    - f_vimrc
    - f_vim_colors_tomorrow-night.vim
    - f_vim_colors_tomorrow-night-bright.vim
    - f_ssh_authorized_keys
    - f_docker_config.json
    - f_config_redshift.conf
    variables:
      font_directory: ~/.local/share/fonts
  OSX:
    dotfiles:
    - f_vimrc
    - f_vim_colors_tomorrow-night.vim
    - f_vim_colors_tomorrow-night-bright.vim
    - f_ssh_authorized_keys
    - f_docker_config.json
    - d_fonts
    - d_kubeconfig
    include:
    - common
    variables:
      font_directory: ~/Library/Fonts
      macos_config_script: ~/bin/macos.sh
  adesso:
    dotfiles:
    - f_docker_config.json
    - d_fonts
    - d_kubeconfig
    include:
    - common
    variables:
      font_directory: ~/Library/Fonts
      git_email: tobias.vollmer@adesso-service.com
      git_user: Tobias Vollmer
      macos_config_script: true
trans_write:
  gpg: gpg -qaer 0x16142EF211C6D2340A0B08F0CD7583FE6D62D2A9 -o- {0} > {1}
  gpgdir: tar -c -C {0} . | gpg -qaer 0x16142EF211C6D2340A0B08F0CD7583FE6D62D2A9 -o
    {1}
variables:
  git_email: info@tvollmer.de
  git_user: 5nafu
  MailReader: thunderbird
  WebBrowser: google-chrome
trans_read:
  gpg: gpg -q --for-your-eyes-only --no-tty -d {0} > {1}
  gpgdir: mkdir {1} && gpg -q --for-your-eyes-only --no-tty -d {0} |tar -x -C {1}
